"""Built-in content detectors (the regex half of
:data:`cloudg.mcp.transforms.detectors.DEFAULT_REGISTRY`)."""

from __future__ import annotations

from dataclasses import replace

from cloudg.mcp.transforms.entities import (
    _GUID,
    Detector,
    _ipv6_validator,
    _secret_value,
    _valid_account,
    classify_ip_text,
    looks_like_secret,
)

# ---------------------------------------------------------------------------
# Built-in detectors (order = priority when spans start at the same place)
# ---------------------------------------------------------------------------

_OCTET = r"(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)"
_IPV4 = rf"{_OCTET}(?:\.{_OCTET}){{3}}"
_TLDS = (
    "com|net|org|io|dev|app|cloud|ai|co|biz|info|me|us|uk|de|fr|jp|in|au|ca|eu|nl|se|ch|"
    "es|it|br|sg|kr|cn|ru|internal|local|localdomain|lan|corp|intra|gov|edu|mil|tech|site"
)
_URL_STOP = r"[^\s\"'<>,;)\]}]"

BUILTIN_DETECTORS: tuple[Detector, ...] = (
    Detector(
        "cloudg_uri",
        "cloudg_uri",
        r"cloudg://(?:assets|datasets)/[^\s\"'<>,;)\]}]+",
        category="identifier",
        confidence=0.99,
        min_length=16,
        description="cloudg resource URIs naming an asset or dataset",
    ),
    # -- secrets ---------------------------------------------------------
    Detector(
        "private_key",
        "private_key",
        r"-----BEGIN[ A-Z0-9]*PRIVATE KEY(?: BLOCK)?-----[\s\S]*?"
        r"(?:-----END[ A-Z0-9]*PRIVATE KEY(?: BLOCK)?-----|\Z)",
        category="secret",
        confidence=1.0,
        min_length=30,
        description="PEM / OpenSSH / PGP private key blocks",
    ),
    Detector(
        "jwt",
        "jwt",
        r"\beyJ[A-Za-z0-9_\-]{5,}\.eyJ[A-Za-z0-9_\-]{5,}\.[A-Za-z0-9_\-]*",
        category="secret",
        confidence=0.95,
        min_length=20,
        description="JSON Web Tokens",
    ),
    Detector(
        "url_credentials",
        "password",
        r"\b[a-zA-Z][a-zA-Z0-9+.\-]{1,20}://[^\s:/@\"'<>]*:([^\s@/\"'<>]+)@",
        category="secret",
        confidence=0.95,
        group=1,
        min_length=10,
        validator=_secret_value,
        description="Password in the userinfo part of a URL",
    ),
    Detector(
        "url_userinfo",
        "url_username",
        r"\b[a-zA-Z][a-zA-Z0-9+.\-]{1,20}://([^\s:/@\"'<>]+)@",
        category="pii",
        confidence=0.9,
        group=1,
        min_length=8,
        description="User name in the userinfo part of a URL (no password)",
    ),
    Detector(
        "connection_string_secret",
        "password",
        r"(?i:(?:password|pwd|accountkey|sharedaccesskey|sharedsecret|clientsecret)\s*=\s*)"
        r"([^;\s\"']+)",
        category="secret",
        confidence=0.95,
        group=1,
        min_length=6,
        validator=_secret_value,
        description="Secret parts of key=value;... connection strings",
    ),
    Detector(
        "aws_secret_access_key",
        "aws_secret_access_key",
        r"(?i:aws.{0,20}?(?:secret|sk).{0,20}?[\"'\s:=]{1,20})([A-Za-z0-9/+=]{40})(?![A-Za-z0-9/+=])",
        category="secret",
        confidence=0.95,
        group=1,
        min_length=40,
        description="AWS secret access keys next to an aws_secret_* label",
    ),
    Detector(
        "secret_assignment",
        "secret_value",
        r"(?i:\b(?:password|passwd|pwd|secret|client[_-]?secret|api[_-]?key|apikey|"
        r"access[_-]?token|auth[_-]?token|refresh[_-]?token|bearer|token|private[_-]?key|"
        r"secret[_-]?key|passphrase)\b[\"']?\s*[:=]\s*[\"']?)([^\s\"',;}{]{4,})",
        category="secret",
        confidence=0.85,
        group=1,
        min_length=8,
        validator=_secret_value,
        description="A password, token or API key assigned a value inside text",
    ),
    Detector(
        "authorization_header",
        "secret_value",
        r"(?i:\b(?:bearer|basic)\s+)([A-Za-z0-9\-._~+/]{16,}=*)",
        category="secret",
        confidence=0.9,
        group=1,
        min_length=20,
        description="HTTP Authorization header credentials",
    ),
    Detector(
        "github_token",
        "api_token",
        r"\b(?:gh[pousr]_[A-Za-z0-9]{36,255}|github_pat_[A-Za-z0-9_]{22,255})\b",
        category="secret",
        confidence=0.99,
        min_length=30,
    ),
    Detector(
        "slack_token",
        "api_token",
        r"\bxox[abposr]-[A-Za-z0-9\-]{10,}\b",
        category="secret",
        confidence=0.99,
        min_length=15,
    ),
    Detector(
        "google_api_key",
        "api_token",
        r"\bAIza[0-9A-Za-z_\-]{35}\b",
        category="secret",
        confidence=0.99,
        min_length=39,
    ),
    Detector(
        "stripe_key",
        "api_token",
        r"\b(?:sk|rk|pk)_(?:live|test)_[0-9A-Za-z]{16,}\b",
        category="secret",
        confidence=0.99,
        min_length=24,
    ),
    Detector(
        "azure_sas_signature",
        "secret_value",
        r"(?i:\bsig=)([A-Za-z0-9%+/=]{20,})",
        category="secret",
        confidence=0.95,
        group=1,
        min_length=24,
        description="Signature of an Azure shared access signature URL",
    ),
    Detector(
        "azure_storage_key",
        "secret_value",
        r"(?<![A-Za-z0-9+/])[A-Za-z0-9+/]{86}==(?![A-Za-z0-9+/=])",
        category="secret",
        confidence=0.8,
        min_length=88,
        description="88-character base64 Azure storage account keys",
    ),
    # -- credentials / identifiers ----------------------------------------
    Detector(
        "aws_access_key_id",
        "aws_access_key_id",
        r"\b(?:AKIA|ASIA)[A-Z0-9]{16}\b",
        category="credential",
        confidence=0.99,
        min_length=20,
        description="AWS access key IDs (long-term AKIA, temporary ASIA)",
    ),
    Detector(
        "aws_unique_id",
        "aws_unique_id",
        r"\b(?:AIDA|AROA|AGPA|AIPA|ANPA|ANVA|APKA|ABIA|ACCA)[A-Z0-9]{16,17}\b",
        category="identifier",
        confidence=0.95,
        min_length=20,
        description="AWS IAM unique IDs (users, roles, groups...)",
    ),
    Detector(
        "aws_org_id",
        "aws_org_id",
        r"\bo-[a-z0-9]{10,32}\b",
        category="identifier",
        confidence=0.85,
        min_length=12,
        description="AWS Organizations organization ids",
    ),
    Detector(
        "aws_ou_id",
        "aws_ou_id",
        r"\bou-[a-z0-9]{4,32}-[a-z0-9]{8,32}\b",
        category="identifier",
        confidence=0.9,
        min_length=16,
        description="AWS Organizations organizational unit ids",
    ),
    Detector(
        "aws_root_id",
        "aws_root_id",
        r"(?<![\w\-])r-[a-z0-9]{4,32}\b(?!-)",
        category="identifier",
        confidence=0.7,
        min_length=6,
        description="AWS Organizations root ids",
    ),
    Detector(
        "cloudg_iri",
        "cloudg_iri",
        r"(?:\bcmr:|https://cloudg\.io/resource/)[^\s\"'<>,;)\]}]+",
        category="identifier",
        confidence=0.95,
        min_length=6,
        description="cloudg ontology resource IRIs (assets, tags) embedding identifiers",
    ),
    Detector(
        "aws_arn",
        "aws_arn",
        r"\barn:(?:aws|aws-cn|aws-us-gov|aws-iso(?:-[a-z])?):[a-zA-Z0-9\-]*:[a-z0-9\-]*:"
        rf"(?:\d{{12}}|aws)?:{_URL_STOP}+",
        category="identifier",
        confidence=0.99,
        min_length=12,
    ),
    Detector(
        "azure_resource_id",
        "azure_resource_id",
        rf"(?i:/subscriptions/{_GUID}(?:/[^\s/\"'<>,;?#]+)*)",
        category="identifier",
        confidence=0.99,
        min_length=50,
    ),
    Detector(
        "gcp_resource_name",
        "gcp_resource_name",
        r"//[a-z0-9\-]+\.googleapis\.com/[^\s/\"'<>,;?#]+(?:/[^\s/\"'<>,;?#]+)*/?"
        r"|\b(?:projects|organizations|folders)/(?:[a-z][a-z0-9\-]{4,28}[a-z0-9]|\d{6,20})"
        r"(?:/[^\s/\"'<>,;?#]+)*",
        category="identifier",
        confidence=0.95,
        min_length=12,
        description="GCP full resource names (//svc.googleapis.com/...) and relative names",
    ),
    Detector(
        "azure_subscription_ref",
        "azure_subscription_id",
        rf"(?i:(?:subscription|tenant)[_ ]?id[\"']?\s*[:=]\s*[\"']?)({_GUID})",
        category="identifier",
        confidence=0.9,
        group=1,
        min_length=40,
    ),
    Detector(
        "email",
        "email",
        r"\b[A-Za-z0-9._%+\-]{1,64}@[A-Za-z0-9]+(?:-+[A-Za-z0-9]+)*"
        r"(?:\.[A-Za-z0-9]+(?:-+[A-Za-z0-9]+)*){0,32}\.[A-Za-z]{2,24}\b",
        category="pii",
        confidence=0.95,
        min_length=6,
    ),
    # -- network ---------------------------------------------------------
    Detector(
        "ipv6",
        "ip_address",
        r"(?<![0-9A-Fa-f:.])(?:[0-9A-Fa-f]{0,4}:){2,7}[0-9A-Fa-f]{0,4}(?:/\d{1,3})?"
        r"(?![0-9A-Fa-f:])",
        category="network",
        confidence=0.9,
        validator=_ipv6_validator,
        min_length=2,
        description="IPv6 addresses and CIDRs (validated with ipaddress)",
    ),
    Detector(
        "ipv4",
        "ip_address",
        rf"(?<![\d.]){_IPV4}(?:/(?:3[0-2]|[12]?\d))?(?!\.?\d)",
        category="network",
        confidence=0.9,
        validator=classify_ip_text,
        min_length=7,
        description="IPv4 addresses and CIDRs (validated with ipaddress)",
    ),
    Detector(
        "mac_address",
        "mac_address",
        r"\b[0-9A-Fa-f]{2}(?:[:\-][0-9A-Fa-f]{2}){5}\b",
        category="network",
        confidence=0.8,
        min_length=17,
    ),
    Detector(
        "hostname",
        "hostname",
        rf"(?i:\b(?:[a-z0-9](?:[a-z0-9\-]{{0,61}}[a-z0-9])?\.){{1,32}}(?:{_TLDS})\b)(?![\-.]?\w)",
        category="network",
        confidence=0.7,
        min_length=4,
        description="Fully-qualified DNS names with a common TLD",
    ),
    Detector(
        "aws_account_id",
        "aws_account_id",
        r"(?<![A-Za-z0-9_.\-/])\d{12}(?![A-Za-z0-9_\-]|\.\d)",
        category="identifier",
        confidence=0.7,
        validator=_valid_account,
        min_length=12,
        description="Bare 12-digit numbers (AWS account IDs)",
    ),
    # -- low-confidence / opt-in -----------------------------------------
    Detector(
        "timestamp",
        "timestamp",
        r"\b\d{4}-\d{2}-\d{2}[T ]\d{2}:\d{2}(?::\d{2}(?:\.\d+)?)?(?:Z|[+\-]\d{2}:?\d{2})?",
        category="temporal",
        confidence=0.9,
        min_length=16,
    ),
    Detector(
        "uuid",
        "uuid",
        rf"\b{_GUID}\b",
        category="identifier",
        confidence=0.6,
        min_length=36,
        description="Generic UUIDs (opt in only: cloudg's own asset IDs are UUIDs)",
    ),
    Detector(
        "high_entropy_secret",
        "secret_value",
        r"(?<![A-Za-z0-9+/_\-])[A-Za-z0-9+/_\-]{32,}={0,2}(?![A-Za-z0-9+/=_\-])",
        category="secret",
        confidence=0.5,
        validator=looks_like_secret,
        min_length=32,
        description="Opaque high-entropy tokens (mixed case + digits, entropy >= 4 bits/char)",
    ),
)

_HINTS: dict[str, tuple[str, ...]] = {
    "private_key": ("private key",),
    "jwt": ("eyj",),
    "url_credentials": ("://",),
    "url_userinfo": ("://",),
    "cloudg_uri": ("cloudg://",),
    "aws_org_id": ("o-",),
    "aws_ou_id": ("ou-",),
    "aws_root_id": ("r-",),
    "cloudg_iri": ("cmr:", "cloudg.io/resource/"),
    "connection_string_secret": (
        "password",
        "pwd",
        "accountkey",
        "sharedaccesskey",
        "sharedsecret",
        "clientsecret",
    ),
    "aws_secret_access_key": ("aws",),
    "secret_assignment": ("pass", "pwd", "secret", "key", "token", "bearer"),
    "authorization_header": ("bearer", "basic"),
    "github_token": ("gh", "github_pat_"),
    "slack_token": ("xox",),
    "google_api_key": ("aiza",),
    "stripe_key": ("_live_", "_test_"),
    "azure_sas_signature": ("sig=",),
    "azure_storage_key": ("==",),
    "aws_access_key_id": ("akia", "asia"),
    "aws_unique_id": ("aida", "aroa", "agpa", "aipa", "anpa", "anva", "apka", "abia", "acca"),
    "aws_arn": ("arn:",),
    "azure_resource_id": ("/subscriptions/",),
    "gcp_resource_name": ("googleapis.com", "projects/", "organizations/", "folders/"),
    "azure_subscription_ref": ("subscription", "tenant"),
    "email": ("@",),
    "ipv6": (":",),
    "ipv4": (".",),
    "mac_address": (":", "-"),
    "hostname": (".",),
    "aws_account_id": ("0", "1", "2", "3", "4", "5", "6", "7", "8", "9"),
    "timestamp": ("-",),
    "uuid": ("-",),
}
BUILTIN_DETECTORS = tuple(replace(d, hints=_HINTS.get(d.name, ())) for d in BUILTIN_DETECTORS)
