#!/usr/bin/env python3
"""Import compliance framework mappings from a Prowler checkout.

Prowler (https://github.com/prowler-cloud/prowler, Apache-2.0) ships JSON
files that map every compliance requirement of a framework to the Prowler
checks that assess it. This script converts a chosen set of those files
into cloudg ruleset YAML, so the normaliser can tag findings with exact
framework control IDs instead of falling back to regex patterns.

Usage:
    python scripts/import_prowler_compliance.py /path/to/prowler/checkout
    python scripts/import_prowler_compliance.py /path/to/prowler --out cloudg/rules/frameworks

Re-run it whenever you want to refresh the shipped rulesets against a
newer Prowler release.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import yaml

# (provider dir, file stem) pairs to import. Extend as needed.
FRAMEWORKS = [
    ("aws", "cis_5.0_aws"),
    ("aws", "aws_foundational_security_best_practices_aws"),
    ("aws", "nist_800_53_revision_5_aws"),
    ("aws", "nist_csf_2.0_aws"),
    ("aws", "pci_4.0_aws"),
    ("aws", "soc2_aws"),
    ("aws", "hipaa_aws"),
    ("aws", "gdpr_aws"),
    ("aws", "iso27001_2022_aws"),
    ("aws", "mitre_attack_aws"),
    ("azure", "cis_5.0_azure"),
    ("azure", "pci_4.0_azure"),
    ("azure", "soc2_azure"),
    ("azure", "hipaa_azure"),
    ("azure", "iso27001_2022_azure"),
    ("azure", "mitre_attack_azure"),
    ("gcp", "cis_5.0_gcp"),
    ("gcp", "pci_4.0_gcp"),
    ("gcp", "soc2_gcp"),
    ("gcp", "hipaa_gcp"),
    ("gcp", "iso27001_2022_gcp"),
    ("gcp", "mitre_attack_gcp"),
]

MAX_TITLE = 300


def convert(src: Path, out_dir: Path) -> tuple[str, int, int]:
    """Convert one Prowler compliance JSON into a cloudg ruleset YAML."""
    data = json.loads(src.read_text())

    framework = data["Framework"]
    provider = data.get("Provider", "")
    version = data.get("Version", "")
    fw_key = f"{framework}-{provider.upper()}" if provider else framework

    controls = []
    linked = 0
    for req in data.get("Requirements", []):
        checks = req.get("Checks") or []
        if not checks:
            # Manual / procedural requirement — nothing a scanner can map.
            continue
        title = (req.get("Description") or req.get("Name") or "").strip()
        if len(title) > MAX_TITLE:
            title = title[: MAX_TITLE - 1] + "…"
        controls.append(
            {
                "id": str(req["Id"]),
                "title": title,
                "checks": sorted(set(checks)),
            }
        )
        linked += len(checks)

    doc = {
        "framework": fw_key,
        "version": version or None,
        "source": (
            f"Prowler compliance data ({src.name}), Apache-2.0, "
            "https://github.com/prowler-cloud/prowler"
        ),
        "provider": provider.lower(),
        "controls": controls,
    }

    out_path = out_dir / f"{src.stem}.yaml"
    header = (
        "# Generated by scripts/import_prowler_compliance.py — do not edit by hand.\n"
        f"# Framework: {framework} {version} ({provider})\n"
        "# Data source: Prowler (https://github.com/prowler-cloud/prowler), Apache-2.0.\n"
    )
    out_path.write_text(header + yaml.safe_dump(doc, sort_keys=False, allow_unicode=True))
    return fw_key, len(controls), linked


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("prowler_path", type=Path, help="Path to a Prowler checkout")
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("cloudg/rules/frameworks"),
        help="Output directory for generated rulesets",
    )
    args = parser.parse_args()

    compliance_root = args.prowler_path / "prowler" / "compliance"
    if not compliance_root.is_dir():
        print(f"error: {compliance_root} not found — is this a Prowler checkout?")
        return 1

    args.out.mkdir(parents=True, exist_ok=True)
    total_controls = total_links = 0
    for provider_dir, stem in FRAMEWORKS:
        src = compliance_root / provider_dir / f"{stem}.json"
        if not src.exists():
            print(f"skip: {src} not found")
            continue
        fw, n_controls, n_links = convert(src, args.out)
        total_controls += n_controls
        total_links += n_links
        print(
            f"{fw}: {n_controls} controls, {n_links} check links -> {args.out / (stem + '.yaml')}"
        )

    print(f"\nTotal: {total_controls} controls, {total_links} check links")
    return 0


if __name__ == "__main__":
    sys.exit(main())
